# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 924990fb63952cd3b401353f22c8265cbb58bd64b228567a2d0f078510f2c84f8fd2a05bd262048c1a248cf2ff2f3b1ef2801b6f714e51e586bbe023319782c5

test:
  secret_key_base: 025a1f6865599d6f26087668dc31ee3cac2d00ac3fc481064e744cdf09ac36ae2c2c18b612799a2779382dad2012c2ea652bf55b6f02c6cb06de6bd36d592956

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
